version: '3.8'

services:
  db:
    image: postgres:12
    env_file:
      - deploy.env
    ports:
      - 5432:5432

  backend:
    build: .
    env_file:
      - deploy.env
    depends_on:
      - db
    ports:
      - 8000:8000